config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :posts, only: %i[create show update edit destroy new] do
    resources :comments, only: %i[create], module: :posts

    resources :likes, only: %i[create destroy], module: :posts
  end

  root 'home#index'
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  has_many :posts, dependent: :destroy

  validates :name, presence: true
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  belongs_to :category
  belongs_to :creator, class_name: 'User'
  has_many :comments, class_name: 'PostComment', dependent: :destroy
  has_many :likes, class_name: 'PostLike', dependent: :destroy

  validates :title, :body, presence: true

  def like_by_user(user)
    return nil unless user

    likes.find_by(user_id: user.id)
  end
end

app/models/post_comment.rb
# frozen_string_literal: true

class PostComment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  has_ancestry

  validates :content, presence: true

  def descendant_comments
    child_ids.each_with_object([]) do |id, arr|
      arr << PostComment.find(id)
    end
  end
end

app/models/post_like.rb
# frozen_string_literal: true

class PostLike < ApplicationRecord
  belongs_to :post, counter_cache: :likes_count
  belongs_to :user

  validates :user_id, uniqueness: { scope: :post_id }
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :likes, class_name: 'PostLike', dependent: :destroy
  has_many :comments, class_name: 'PostComment', dependent: :destroy
  has_many :posts, class_name: 'Post', foreign_key: 'creator_id', dependent: :destroy
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index
    @posts = Post.includes(:creator, :category, :likes).order(created_at: :desc)
  end
end

app/controllers/posts/application_controller.rb
# frozen_string_literal: true

class Posts::ApplicationController < ApplicationController
  def resource_post
    @resource_post ||= Post.find params[:post_id]
  end
end

app/controllers/posts/comments_controller.rb
# frozen_string_literal: true

class Posts::CommentsController < Posts::ApplicationController
  before_action :authenticate_user!

  def create
    @post_comment = resource_post.comments.build(post_comment_params)
    @post_comment.user_id = current_user.id

    if @post_comment.save
      redirect_to post_url(resource_post), notice: t('.success')
    else
      redirect_to post_url(resource_post), alert: @post_comment.errors.full_messages.join(', ')
    end
  end

  private

  # Only allow a list of trusted parameters through.
  def post_comment_params
    params.require(:post_comment).permit(:content, :parent_id)
  end
end

app/controllers/posts/likes_controller.rb
# frozen_string_literal: true

class Posts::LikesController < Posts::ApplicationController
  before_action :authenticate_user!

  def create
    @post_like = resource_post.likes.create(user_id: current_user.id)

    # Just refresh current page or redirect to to root if refferer is unknown
    redirect_back(fallback_location: root_path)
  end

  def destroy
    @post_like = resource_post.likes.find_by(user: current_user)&.destroy

    redirect_back(fallback_location: root_path)
  end
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  before_action :authenticate_user!, only: %i[new edit create update destroy]

  # GET /posts/1 or /posts/1.json
  def show
    @post = Post.find(params[:id])
    @comments = @post.comments.includes(:user).arrange
    @new_comment = @post.comments.build
    @users_liked = @post.likes.includes(:user).map { |like| like.user.email[/\w+/] }.join(', ')
    @like_by_user = @post.like_by_user(current_user)
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
    @post = current_user.posts.find(params[:id])
  end

  # POST /posts or /posts.json
  def create
    @post = current_user.posts.build(post_params)

    if @post.save
      redirect_to post_url(@post), notice: t('.success')
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /posts/1
  def update
    @post = current_user.posts.find(params[:id])

    if @post.update(post_params)
      redirect_to post_url(@post), notice: t('.success')
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /posts/1
  def destroy
    @post = current_user.posts.find(params[:id])

    @post.destroy
    redirect_to root_path, notice: t('.success')
  end

  private

  # Only allow a list of trusted parameters through.
  def post_params
    params.require(:post).permit(:title, :body, :category_id)
  end
end

app/views/home/index.html.slim
.container
  h1 = t('home.title')
  h4 = t('home.all_posts')
  br
  .d-flex.flex-column
      - @posts.each do |post|
        .border.rounded
          .p-2
            h4
              = link_to post.title, post_path(post), class: 'link-dark text-decoration-none me-2'
            p.fw-bold.mb-1 #{t('posts.params.category')} #{post.category.name}
            p.mb-2 #{t('posts.params.author')} #{post.creator.email[/\w+/]}
            p.bg-light.mb-2 = post.body
            == render partial: 'posts/likes/like', locals: { post: post, like_by_user: post.like_by_user(current_user) }
            .text-muted
              small = t('posts.params.liked')
              - if post.likes.size.zero?
                small = t('posts.params.no_likes')
              - else
                small = post.likes.each_with_object([]) { |like, array| array << like.user.email[/\w+/] }.join(', ')
              br
              small = t('posts.params.created', created: time_ago_in_words(post.created_at))
            .d-flex.flex-sm-row
              - if current_user && post.creator == current_user
                = link_to t('posts.links.edit'), edit_post_path(post), class: 'me-2'
                = link_to t('posts.links.delete'), post_path(post), data: { confirm: t('posts.links.destroy_confirmation') }, method: :delete, class: 'text-danger'
        br

  = link_to t('posts.links.new_post'), new_post_path, class: 'btn btn-primary mb-2'

app/views/layouts/_nav.html.slim
.container
  header.d-flex.flex-wrap.align-items-center.justify-content-between.justify-content-md-between.py-3.mb-4.border-bottom
    - if user_signed_in?
      h4 = "#{t('navigation.hello')}, #{current_user.email[/\w+/]}!"
    - else
      h4
    ul.nav.nav-pills
      nav_menu_item = link_to t('navigation.links.home'), root_path, class: 'nav-link'
      - if user_signed_in?
        nav_menu_item = link_to t('posts.links.new_post'), new_post_path, class: 'nav-link'
        nav_menu_item = link_to t('navigation.links.log_out'), destroy_user_session_path, method: :delete, class: 'nav-link'
      -else
        nav_menu_item = link_to t('navigation.links.log_in'), new_user_session_path, class: 'nav-link'
        nav_menu_item = link_to t('navigation.links.registration'), new_user_registration_path, class: 'nav-link'

app/views/layouts/application.html.slim
doctype html
html
  head
    title = t(:title)
    meta[name="viewport" content="width=device-width,initial-scale=1"]
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  body
    = render 'layouts/nav'
    .container
      .my-4
        - if flash[:notice]
          .alert.alert-info = flash[:notice]
        - if flash[:alert]
          .alert.alert-danger = flash[:alert]
    = yield

app/views/posts/_form.html.slim
.container
  = simple_form_for post do |f|
    = f.input :title
    = f.association :category, as: :select, prompt: t('simple_form.prompts.posts.select_category')
    = f.input :body, as: :text
    = f.button :submit, class: 'btn btn-primary mt-2'

app/views/posts/comments/_comment.html.slim
.p-2
  p.mb-0.fw-bold.text-secondary = "#{comment.user.email[/\w+/]}:"
  p.mb-0 = comment.content
  a[class="small text-muted" data-bs-toggle="collapse" href="#new_post_comment-#{comment.id}"] = t('posts.comments.links.add_reply')
  div[class="collapse" data-bs-target="#new_post_comment-#{comment.id}" id="new_post_comment-#{comment.id}"]
    == render partial: 'posts/comments/form', locals: { new_comment: new_comment, post: post, comment: comment }
  - children.each do |comment, children|
    == render partial: 'posts/comments/comment', locals: { comment: comment, children: children, post: post, new_comment: new_comment }

app/views/posts/comments/_form.html.slim
.container
  = simple_form_for new_comment, url: post_comments_path(post.id), method: :post do |f|
    = f.input :content, as: :text
    - if comment
      = f.input :parent_id, as: :hidden, input_html: { value: comment.id }
    = f.button :submit, t('posts.comments.buttons.submit'), class: 'btn btn-primary mt-2'

app/views/posts/edit.html.slim
.container
  h1 = t('posts.titles.edit')

  == render partial: 'form', locals: { post: @post }

  => link_to t('posts.links.show'), @post, class: 'm-2'
  '|
  =< link_to t('posts.links.back'), :back, class: 'm-2'

app/views/posts/likes/_like.html.slim
- if current_user && like_by_user
  span.fw-bold = post.likes.size
  = link_to post_like_path(post.id, like_by_user), method: :delete do
    i.bi.bi-hand-thumbs-up-fill
- else
  span = post.likes.size
  = link_to post_likes_path(post), method: :post do
    i.bi.bi-hand-thumbs-up

app/views/posts/new.html.slim
.container
  h1 = t('posts.titles.new')
  == render partial: 'form', locals: { post: @post }
  = link_to t('posts.links.back'), :back, class: 'm-2'

app/views/posts/show.html.slim
.container
  .d-flex.flex-column
      .border.rounded
        .p-2
          h4 = @post.title
          p.fw-bold.mb-0 #{t('posts.params.category')} #{@post.category.name}
          p.mb-2 #{t('posts.params.author')} #{@post.creator.email[/\w+/]}
          p.bg-light.mb-2.mt-2 = @post.body
          == render partial: 'posts/likes/like', locals: { post: @post, like_by_user: @like_by_user }
          .text-muted
            small #{t('posts.params.liked')} #{@users_liked.empty? ? t('posts.params.no_likes') : @users_liked}
            br
            small = t('posts.params.created', created: time_ago_in_words(@post.created_at))
            br
          span = t('posts.params.comments')
          br
          .border.border-dark.rounded.mt-2
            == render partial: 'posts/comments/form', locals: { new_comment: @new_comment, post: @post, comment: nil }
          - @comments&.each do |comment, children|
            .border.border-dark.rounded.mt-2
              == render partial: 'posts/comments/comment', locals: { comment: comment, children: children, post: @post, new_comment: @new_comment }
          .d-flex.flex-sm-row
            - if current_user && @post.creator == current_user
              = link_to t('posts.links.edit'), edit_post_path(@post), class: 'me-2'
              = link_to t('posts.links.delete'), post_path(@post), data: { confirm: t('posts.links.destroy_confirmation') }, method: :delete, class: 'text-danger'